name: Deploy images

on:
  - push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/rules-as-code
  
jobs:
  delploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    -  name: Checkout
       uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker image
      id: meta_openfisca
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
          context: ./images/rules-as-code
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_openfisca.outputs.tags }}
